In [16]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import scipy.stats as stats
from statsmodels.stats.weightstats import ztest as ztest
from scipy.stats import pearsonr
from scipy.stats import chi2_contingency
import statsmodels.api as sm
from statsmodels.formula.api import ols
from sklearn import preprocessing
from sklearn.preprocessing import LabelBinarizer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MaxAbsScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn import metrics
import pickle

In [17]:
df = pd.read_csv("./boston.csv")
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.9

In [18]:
print(df.columns)

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'MEDV'],
      dtype='object')

In [19]:
X = pd.DataFrame(df.iloc[:,:-1])
y = pd.DataFrame(df.iloc[:,-1])

In [20]:
X

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=1)

In [22]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(404, 13)
(404, 1)
(102, 13)
(102, 1)

In [23]:


# Select features (AGE and LSTAT) and target (MEDV)
X = df[['AGE', 'LSTAT']]
y = df['MEDV']

# Split data into training and testing sets with an 80:20 ratio and random_state = 10
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

# Apply log transformation to the training data features
X_train_log = np.log(X_train)
X_test_log = np.log(X_test)

# Build and train the Linear Regression model
model = LinearRegression()
model.fit(X_train_log, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test_log)

# Calculate R^2 on the test set
r2_test = metrics.r2_score(y_test, y_pred)

print("R^2 on the test set:", r2_test)

R^2 on the test set: 0.619670641748842

In [24]:

X = df[['AGE', 'LSTAT']]
y = df['MEDV']

# Split data into training and testing sets with an 80:20 ratio and random_state = 10
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

# Apply log transformation to the training data features
X_train_log = np.log(X_train)

# Build and train the Linear Regression model
model = LinearRegression()
model.fit(X_train_log, y_train)

# Extract the coefficient for 'LSTAT'
lstat_coef = model.coef_[1]  # 'LSTAT' is the second feature in the training data
print("Há»‡ sá»‘ gÃ³c cá»§a Ä‘áº·c trÆ°ng LSTAT:", lstat_coef)

Há»‡ sá»‘ gÃ³c cá»§a Ä‘áº·c trÆ°ng LSTAT: -13.992359681693534

In [12]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [13]:
from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error, mean_squared_error
print("Score or R-squared: ", model.score(X_test, y_test))
print("Mean absolute Error: ", mean_absolute_error(y_test,y_pred))
print("Root mean squared Error: ", np.sqrt(mean_squared_error(y_test,y_pred)))
print("Mean absolute Percentage Error: ", mean_absolute_percentage_error(y_test,y_pred))
print("Slove - coef: ", model.coef_)
print("Intercep: ", model.intercept_)

Score or R-squared:  0.7634174432138467
Mean absolute Error:  3.750712180838915
Root mean squared Error:  4.835373458200542
Mean absolute Percentage Error:  0.18776351124030594
Slove - coef:  [[-1.12386867e-01  5.80587074e-02  1.83593559e-02  2.12997760e+00
  -1.95811012e+01  3.09546166e+00  4.45265228e-03 -1.50047624e+00
   3.05358969e-01 -1.11230879e-02 -9.89007562e-01  7.32130017e-03
  -5.44644997e-01]]
Intercep:  [42.93352585]

In [25]:


# Select features (AGE and LSTAT) and target (MEDV)
X = df[['AGE', 'LSTAT']]
y = df['MEDV']

# Split data into training and testing sets with an 80:20 ratio and random_state = 10
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

# Apply log transformation to the training data features
X_train_log = np.log(X_train)

# Build and train the Linear Regression model
model = LinearRegression()
model.fit(X_train_log, y_train)

# Extract the intercept
intercept = model.intercept_
print("Há»‡ sá»‘ tá»± do (intercept):", intercept)

Há»‡ sá»‘ tá»± do (intercept): 43.86038526154313